server:
  http2:
    enabled: true
  shutdown: graceful
  tomcat:
    threads:
      max: 20

spring:
  main:
    lazy-initialization: true
    banner-mode: off
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: '@project.name@'
    version: '@project.version@'
  jpa:
    show-sql: true
    generate-ddl: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
  endpoints:
    access:
      default: none
    web:
      exposure:
        include:
        - info
        - health
        - loggers
        - metrics
        - prometheus
        - shutdown
  endpoint:
    health:
      access: unrestricted
    info:
      access: read-only
    loggers:
      access: unrestricted
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted
    shutdown:
      access: unrestricted

logging:
  level:
    root: info
    '[org.springframework.data]': debug



security:
  jwt:
    public-key: ${JWT_PUBLIC_KEY_LOCATION}
    private-key: ${JWT_PRIVATE_KEY_LOCATION}
    issuer: ${JWT_ISSUER:task-manager}
    expiration: ${JWT_EXPIRATION:PT1H}
